import { useEffect, useMemo, useState } from 'react';
import * as WebBrowser from 'expo-web-browser';
import { CalendarDays, ExternalLink, MapPin, Search, Users, X } from 'lucide-react-native';
import { FlatList, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';

import { Card, EmptyState, Loading, PageHeader, Screen, useAppTheme } from '@/components/ui';
import { fetchUpcomingCompetitions, fetchWcaCountries, countryFlag, eventName, registrationStatus, sortEventIds, type WcaCompetition, type WcaCountry } from '@/core/wca';
import { readJson, storageKeys, writeJson } from '@/core/storage';

export default function CompetitionsScreen() {
  const colors = useAppTheme(); const [countries, setCountries] = useState<WcaCountry[]>([]); const [country, setCountry] = useState('IN'); const [selector, setSelector] = useState(false); const [competitions, setCompetitions] = useState<WcaCompetition[]>([]); const [filter, setFilter] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { void Promise.all([fetchWcaCountries(), readJson<string>(storageKeys.competitionCountry, 'IN')]).then(([list, saved]) => { setCountries(list); setCountry(saved); }).catch(() => setError('Could not load the country list.')); }, []);
  useEffect(() => { if (!country) return; let cancelled = false; setLoading(true); setError(''); const cacheKey = `upcoming.${country}.v1`; void readJson<WcaCompetition[]>(cacheKey, []).then((cached) => { if (!cancelled && cached.length) setCompetitions(cached); }); void fetchUpcomingCompetitions(country).then((result) => { if (!cancelled) { setCompetitions(result.competitions); void writeJson(cacheKey, result.competitions); } }).catch(() => { if (!cancelled) setError('Could not refresh competitions. Cached results are shown when available.'); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [country]);
  const visible = useMemo(() => { const needle = filter.trim().toLowerCase(); return competitions.filter((item) => !needle || `${item.name} ${item.city} ${item.venue}`.toLowerCase().includes(needle)); }, [competitions, filter]);
  const selectedCountry = countries.find((item) => item.iso2 === country);
  return <Screen><PageHeader eyebrow="Official WCA calendar" title="Competitions" description="Choose a country, then filter by competition, city, state or venue." /><View style={styles.filters}><Pressable onPress={() => setSelector(true)} style={[styles.country, { borderColor: colors.border, backgroundColor: colors.backgroundElement }]}><Text style={[styles.countryText, { color: colors.text }]}>{countryFlag(country)} {selectedCountry?.name ?? country}</Text></Pressable><View style={[styles.search, { borderColor: colors.border, backgroundColor: colors.backgroundElement }]}><Search color={colors.textSecondary} size={18} /><TextInput value={filter} onChangeText={setFilter} placeholder="Filter competitions…" placeholderTextColor={colors.textSecondary} style={[styles.input, { color: colors.text }]} /></View></View>{error ? <Text style={[styles.error, { color: colors.warning, borderColor: colors.warning }]}>{error}</Text> : null}{loading && !competitions.length ? <Loading label="Loading competitions…" /> : visible.length ? <View style={styles.list}>{visible.map((item) => <CompetitionCard key={item.id} competition={item} />)}</View> : <EmptyState title="No competitions found" body={filter ? 'Nothing matches this filter.' : 'No upcoming competitions have been announced here yet.'} />}<CountryModal open={selector} countries={countries} onClose={() => setSelector(false)} onSelect={(iso2) => { setCountry(iso2); setSelector(false); void writeJson(storageKeys.competitionCountry, iso2); }} /></Screen>;
}

function CompetitionCard({ competition }: { competition: WcaCompetition }) {
  const colors = useAppTheme(); const status = competition.cancelled_at ? 'cancelled' : registrationStatus(competition); const statusText = { open: 'Registration open', not_yet_open: 'Opens soon', closed: 'Registration closed', unknown: '', cancelled: 'Cancelled' }[status];
  return <Pressable onPress={() => void WebBrowser.openBrowserAsync(competition.url)}><Card style={styles.card}><View style={styles.cardHeader}><Text style={[styles.title, { color: colors.text }]}>{competition.short_display_name}</Text>{statusText ? <Text style={[styles.badge, { color: status === 'open' ? colors.success : colors.textSecondary, borderColor: status === 'open' ? colors.success : colors.border }]}>{statusText}</Text> : null}</View><View style={styles.detail}><CalendarDays color={colors.textSecondary} size={16} /><Text style={[styles.detailText, { color: colors.textSecondary }]}>{competition.date_range}</Text></View><View style={styles.detail}><MapPin color={colors.textSecondary} size={16} /><Text style={[styles.detailText, { color: colors.textSecondary }]}>{competition.city} · {competition.venue.replace(/\[|\]|\(.*?\)/g, '')}</Text></View>{competition.competitor_limit ? <View style={styles.detail}><Users color={colors.textSecondary} size={16} /><Text style={[styles.detailText, { color: colors.textSecondary }]}>{competition.competitor_limit} competitor limit</Text></View> : null}<View style={styles.events}>{sortEventIds(competition.event_ids).slice(0, 9).map((id) => <Text key={id} style={[styles.event, { color: colors.primary, backgroundColor: colors.primaryMuted }]}>{eventName(id)}</Text>)}</View><View style={styles.open}><Text style={[styles.openText, { color: colors.primary }]}>Details & registration</Text><ExternalLink color={colors.primary} size={15} /></View></Card></Pressable>;
}

function CountryModal({ open, countries, onClose, onSelect }: { open: boolean; countries: WcaCountry[]; onClose: () => void; onSelect: (iso2: string) => void }) {
  const colors = useAppTheme(); const [search, setSearch] = useState(''); const visible = countries.filter((item) => `${item.name} ${item.iso2}`.toLowerCase().includes(search.toLowerCase()));
  return <Modal visible={open} animationType="slide" presentationStyle="pageSheet" onRequestClose={onClose}><View style={[styles.modal, { backgroundColor: colors.background }]}><View style={styles.modalHeader}><Text style={[styles.modalTitle, { color: colors.text }]}>Choose country</Text><Pressable onPress={onClose} style={styles.close}><X color={colors.text} size={22} /></Pressable></View><View style={[styles.search, { borderColor: colors.border, backgroundColor: colors.backgroundElement }]}><Search color={colors.textSecondary} size={18} /><TextInput autoFocus value={search} onChangeText={setSearch} placeholder="Search countries…" placeholderTextColor={colors.textSecondary} style={[styles.input, { color: colors.text }]} /></View><FlatList data={visible} keyExtractor={(item) => item.iso2} renderItem={({ item }) => <Pressable onPress={() => onSelect(item.iso2)} style={[styles.countryRow, { borderBottomColor: colors.border }]}><Text style={styles.flag}>{countryFlag(item.iso2)}</Text><Text style={[styles.countryName, { color: colors.text }]}>{item.name}</Text><Text style={{ color: colors.textSecondary }}>{item.iso2}</Text></Pressable>} /></View></Modal>;
}

const styles = StyleSheet.create({ filters: { gap: 9, marginBottom: 14 }, country: { minHeight: 48, justifyContent: 'center', borderWidth: StyleSheet.hairlineWidth, borderRadius: 14, paddingHorizontal: 14 }, countryText: { fontSize: 15, fontWeight: '800' }, search: { minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 8, borderWidth: StyleSheet.hairlineWidth, borderRadius: 14, paddingHorizontal: 13 }, input: { flex: 1, fontSize: 15 }, error: { borderWidth: StyleSheet.hairlineWidth, borderRadius: 12, padding: 12, marginBottom: 12 }, list: { gap: 11 }, card: { gap: 8 }, cardHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 8 }, title: { flex: 1, fontSize: 18, lineHeight: 23, fontWeight: '900' }, badge: { fontSize: 10, fontWeight: '900', borderWidth: StyleSheet.hairlineWidth, borderRadius: 10, paddingHorizontal: 7, paddingVertical: 4 }, detail: { flexDirection: 'row', gap: 8, alignItems: 'flex-start' }, detailText: { flex: 1, fontSize: 13, lineHeight: 19 }, events: { flexDirection: 'row', flexWrap: 'wrap', gap: 5, marginTop: 3 }, event: { fontSize: 10, fontWeight: '800', paddingHorizontal: 7, paddingVertical: 4, borderRadius: 8 }, open: { flexDirection: 'row', gap: 6, alignItems: 'center', marginTop: 4 }, openText: { fontSize: 13, fontWeight: '900' }, modal: { flex: 1, paddingTop: 16, paddingHorizontal: 18 }, modalHeader: { minHeight: 52, flexDirection: 'row', alignItems: 'center' }, modalTitle: { flex: 1, fontSize: 24, fontWeight: '900' }, close: { padding: 10 }, countryRow: { minHeight: 54, flexDirection: 'row', alignItems: 'center', gap: 10, borderBottomWidth: StyleSheet.hairlineWidth }, flag: { fontSize: 22 }, countryName: { flex: 1, fontSize: 15, fontWeight: '700' } });
