import { useEffect, useState } from 'react';
import { ChevronDown, Play } from 'lucide-react-native';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import type { PuzzleId } from '@shared/puzzle';

import { Card, Chip, PageHeader, Screen, useAppTheme } from '@/components/ui';
import { PuzzleCanvas } from '@/components/puzzle-viewer/canvas';
import { PuzzleControls } from '@/components/puzzle-viewer/controls';
import { usePuzzleController } from '@/core/puzzle-controller';

interface MoveInfo { code: string; name: string; description: string }
interface MoveSection { title: string; moves: MoveInfo[] }
const BASIC: MoveInfo[] = [
  { code: 'R', name: 'Right', description: 'Right face 90° clockwise' }, { code: 'L', name: 'Left', description: 'Left face 90° clockwise' },
  { code: 'U', name: 'Up', description: 'Top face 90° clockwise' }, { code: 'D', name: 'Down', description: 'Bottom face 90° clockwise' },
  { code: 'F', name: 'Front', description: 'Front face 90° clockwise' }, { code: 'B', name: 'Back', description: 'Back face 90° clockwise' },
];
const CONFIG: Record<string, { id: PuzzleId; sections: MoveSection[]; example: string }> = {
  '3x3': { id: '333', sections: [{ title: 'Basic face moves', moves: BASIC }, { title: 'Move modifiers', moves: [{ code: "R'", name: 'Prime', description: '90° counter-clockwise' }, { code: 'R2', name: 'Double', description: '180° turn' }, { code: 'r', name: 'Wide turn', description: 'Turn two layers together' }] }, { title: 'Middle & slice moves', moves: [{ code: 'M', name: 'Middle', description: 'Middle layer in the L direction' }, { code: 'E', name: 'Equatorial', description: 'Middle layer in the D direction' }, { code: 'S', name: 'Standing', description: 'Middle layer in the F direction' }] }, { title: 'Cube rotations', moves: [{ code: 'x', name: 'X rotation', description: 'Rotate on the R axis' }, { code: 'y', name: 'Y rotation', description: 'Rotate on the U axis' }, { code: 'z', name: 'Z rotation', description: 'Rotate on the F axis' }] }], example: "R U R' U' R' F R2 U' R' U' R U R' F'" },
  '2x2': { id: '222', sections: [{ title: 'Face moves', moves: BASIC }, { title: 'Modifiers', moves: [{ code: "R'", name: 'Prime', description: 'Counter-clockwise turn' }, { code: 'R2', name: 'Double', description: '180° turn' }] }], example: "R U R' U' F' U F R2" },
  '4x4': { id: '444', sections: [{ title: 'Face moves', moves: BASIC.slice(0, 4) }, { title: 'Wide and inner moves', moves: [{ code: 'Rw', name: 'Right wide', description: 'Turn the two right layers' }, { code: 'Uw', name: 'Up wide', description: 'Turn the two top layers' }, { code: '3R', name: 'Inner layer', description: 'Third layer from the right' }] }], example: "Rw U2 Rw' U2 F2" },
  '5x5': { id: '555', sections: [{ title: 'Face moves', moves: BASIC.slice(0, 4) }, { title: 'Wide and inner moves', moves: [{ code: 'Rw', name: 'Right wide', description: 'Turn two layers' }, { code: '3Rw', name: 'Three-layer wide', description: 'Turn three layers' }, { code: '3R', name: 'Inner layer', description: 'Third layer only' }] }], example: "Rw U2 3Rw' F2" },
  '6x6': { id: '666', sections: [{ title: 'Face moves', moves: BASIC.slice(0, 4) }, { title: 'Wide and inner moves', moves: [{ code: 'Rw', name: 'Right wide', description: 'Turn two layers' }, { code: '3Rw', name: 'Three-layer wide', description: 'Turn three layers' }, { code: '3R', name: 'Inner layer', description: 'Third layer only' }] }], example: "3Rw U2 Rw' F2" },
  '7x7': { id: '777', sections: [{ title: 'Face moves', moves: BASIC.slice(0, 4) }, { title: 'Wide and inner moves', moves: [{ code: 'Rw', name: 'Right wide', description: 'Turn two layers' }, { code: '3Rw', name: 'Three-layer wide', description: 'Turn three layers' }, { code: '3R', name: 'Inner layer', description: 'Third layer only' }] }], example: "3Rw U2 Rw' F2" },
  Pyraminx: { id: 'pyraminx', sections: [{ title: 'Face turns', moves: [{ code: 'U', name: 'Upper', description: 'Turn two layers at the upper vertex' }, { code: 'R', name: 'Right', description: 'Turn two layers at the right vertex' }, { code: 'L', name: 'Left', description: 'Turn two layers at the left vertex' }, { code: 'B', name: 'Back', description: 'Turn two layers at the back vertex' }] }, { title: 'Tips', moves: [{ code: 'u', name: 'Upper tip', description: 'Turn only the upper tip' }, { code: 'r', name: 'Right tip', description: 'Turn only the right tip' }, { code: 'l', name: 'Left tip', description: 'Turn only the left tip' }, { code: 'b', name: 'Back tip', description: 'Turn only the back tip' }] }, { title: 'Modifier', moves: [{ code: "U'", name: 'Prime', description: 'Counter-clockwise third turn' }] }], example: "U R' L B l' r' b u" },
};

export default function NotationScreen() {
  const colors = useAppTheme(); const [choice, setChoice] = useState('3x3'); const config = CONFIG[choice]; const controller = usePuzzleController(config.id); const [open, setOpen] = useState(new Set([config.sections[0].title]));
  useEffect(() => { setOpen(new Set([config.sections[0].title])); controller.setBase(''); controller.setTimeline(config.example); }, [choice, config, controller]);
  const show = (algorithm: string) => { controller.setBase(''); controller.setTimeline(algorithm); controller.play(); };
  return <Screen><PageHeader eyebrow="Tap any move" title="Notation guide" description="Every move runs on the same interactive puzzle model used by the solver and algorithm library." /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{Object.keys(CONFIG).map((label) => <Chip key={label} label={label} selected={choice === label} onPress={() => setChoice(label)} />)}</ScrollView><PuzzleCanvas controller={controller} /><PuzzleControls controller={controller} /><Pressable onPress={() => show(config.example)}><Card style={styles.example}><Play color={colors.primary} size={18} /><View style={styles.exampleCopy}><Text style={[styles.exampleLabel, { color: colors.textSecondary }]}>EXAMPLE SEQUENCE</Text><Text style={[styles.exampleMoves, { color: colors.text }]}>{config.example}</Text></View></Card></Pressable><View style={styles.sections}>{config.sections.map((section) => { const expanded = open.has(section.title); return <View key={section.title} style={[styles.section, { borderColor: colors.border, backgroundColor: colors.backgroundElement }]}><Pressable onPress={() => setOpen((current) => { const next = new Set(current); if (next.has(section.title)) next.delete(section.title); else next.add(section.title); return next; })} style={styles.sectionHeader}><ChevronDown color={colors.textSecondary} size={19} style={{ transform: [{ rotate: expanded ? '180deg' : '0deg' }] }} /><Text style={[styles.sectionTitle, { color: colors.text }]}>{section.title}</Text></Pressable>{expanded ? <View style={[styles.moves, { borderTopColor: colors.border }]}>{section.moves.map((move) => <Pressable key={move.code} onPress={() => show(move.code)} style={[styles.move, { borderBottomColor: colors.border }]}><Text style={[styles.code, { color: colors.primary, backgroundColor: colors.primaryMuted }]}>{move.code}</Text><View style={styles.moveCopy}><Text style={[styles.moveName, { color: colors.text }]}>{move.name}</Text><Text style={[styles.moveDescription, { color: colors.textSecondary }]}>{move.description}</Text></View><Play color={colors.textSecondary} size={16} /></Pressable>)}</View> : null}</View>; })}</View></Screen>;
}
const styles = StyleSheet.create({ chips: { gap: 8, paddingBottom: 14 }, example: { marginTop: 14, flexDirection: 'row', alignItems: 'center', gap: 12 }, exampleCopy: { flex: 1, gap: 4 }, exampleLabel: { fontSize: 10, letterSpacing: 1, fontWeight: '900' }, exampleMoves: { fontFamily: 'monospace', fontSize: 13 }, sections: { gap: 9, marginTop: 14 }, section: { borderWidth: StyleSheet.hairlineWidth, borderRadius: 16, overflow: 'hidden' }, sectionHeader: { minHeight: 56, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 14 }, sectionTitle: { fontSize: 18, fontWeight: '900' }, moves: { borderTopWidth: StyleSheet.hairlineWidth }, move: { minHeight: 68, flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 13, borderBottomWidth: StyleSheet.hairlineWidth }, code: { minWidth: 47, textAlign: 'center', overflow: 'hidden', borderRadius: 10, paddingHorizontal: 8, paddingVertical: 10, fontFamily: 'monospace', fontWeight: '900' }, moveCopy: { flex: 1 }, moveName: { fontSize: 15, fontWeight: '800' }, moveDescription: { fontSize: 12, lineHeight: 18 } });
