import { useRef, useState } from 'react';
import { CameraView, useCameraPermissions } from 'expo-camera';
import { router } from 'expo-router';
import * as Haptics from 'expo-haptics';
import { Camera, Keyboard, RotateCcw } from 'lucide-react-native';
import { Dimensions, Pressable, StyleSheet, Text, View } from 'react-native';
import { classifyScan } from '@shared/scanner/classify';
import { faceShapes, SCAN_STEPS } from '@shared/scanner/geometry';
import type { RGB } from '@shared/scanner/sampling';
import type { SolvablePuzzleId } from '@shared/solver/state-mapping';

import { AppButton, Card, Chip, PageHeader, Screen, useAppTheme } from '@/components/ui';
import { sampleJpeg } from '@/core/image-sampling';

const PUZZLES: { id: SolvablePuzzleId; label: string }[] = [{ id: '333', label: '3x3' }, { id: '222', label: '2x2' }, { id: 'pyraminx', label: 'Pyraminx' }];
export default function ScannerScreen() {
  const colors = useAppTheme(); const [permission, requestPermission] = useCameraPermissions(); const camera = useRef<CameraView>(null); const [puzzle, setPuzzle] = useState<SolvablePuzzleId>('333'); const [step, setStep] = useState(0); const [samples, setSamples] = useState<RGB[][]>([]); const [capturing, setCapturing] = useState(false); const [error, setError] = useState(''); const shapes = faceShapes(puzzle); const steps = SCAN_STEPS[puzzle]; const cameraSize = Math.min(Dimensions.get('window').width - 36, 520);
  const reset = (next = puzzle) => { setPuzzle(next); setStep(0); setSamples([]); setError(''); };
  const capture = async () => { if (!camera.current || capturing) return; setCapturing(true); setError(''); try { const photo = await camera.current.takePictureAsync({ base64: true, quality: 0.45, skipProcessing: false }); if (!photo?.base64) throw new Error('The camera did not return image data.'); const face = sampleJpeg(photo.base64, shapes); const next = [...samples, face]; void Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success); if (next.length === steps.length) { const facelets = classifyScan(puzzle, next); router.replace({ pathname: '/solve', params: { puzzle, facelets } }); return; } setSamples(next); setStep((value) => value + 1); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not capture this face.'); } finally { setCapturing(false); } };
  if (!permission) return <Screen><PageHeader title="Camera scanner" /><Text style={{ color: colors.textSecondary }}>Checking camera permission…</Text></Screen>;
  if (!permission.granted) return <Screen><PageHeader eyebrow="Private by design" title="Camera permission" description="CuberVerse samples sticker colors on this device. Captured photos are discarded and never uploaded." /><Card><AppButton onPress={() => void requestPermission()}><View style={styles.inline}><Camera color="#fff" size={18} /><Text style={styles.white}>Allow camera access</Text></View></AppButton><AppButton variant="secondary" onPress={() => router.replace('/solve')}><View style={styles.inline}><Keyboard color={colors.text} size={18} /><Text style={{ color: colors.text, fontWeight: '900' }}>Enter colors manually</Text></View></AppButton></Card></Screen>;
  return <Screen><PageHeader eyebrow="Guided · on-device" title="Camera scanner" description="Line up each face with the guide and capture it in the requested orientation." /><View style={styles.chips}>{PUZZLES.map((item) => <Chip key={item.id} label={item.label} selected={puzzle === item.id} onPress={() => reset(item.id)} />)}</View><View style={styles.progress}>{steps.map((item, index) => <View key={item.face} style={[styles.dot, { backgroundColor: index < step ? colors.success : index === step ? colors.primary : colors.border }]} />)}</View><Card style={styles.instruction}><Text style={[styles.face, { color: colors.primary }]}>Face {step + 1} of {steps.length} · {steps[step].face}</Text><Text style={[styles.instructionText, { color: colors.textSecondary }]}>{steps[step].instruction}</Text></Card><View style={[styles.cameraShell, { width: cameraSize, height: cameraSize, borderColor: colors.border }]}><CameraView ref={camera} style={StyleSheet.absoluteFill} facing="back" mode="picture" /><View pointerEvents="none" style={StyleSheet.absoluteFill}>{shapes.map((shape, index) => { const minX = Math.min(...shape.points.map((point) => point[0])); const maxX = Math.max(...shape.points.map((point) => point[0])); const minY = Math.min(...shape.points.map((point) => point[1])); const maxY = Math.max(...shape.points.map((point) => point[1])); return <View key={index} style={[styles.guide, { left: minX * cameraSize, top: minY * cameraSize, width: (maxX - minX) * cameraSize, height: (maxY - minY) * cameraSize }]} />; })}</View></View>{error ? <Text style={[styles.error, { color: colors.danger }]}>{error}</Text> : null}<View style={styles.actions}><AppButton variant="secondary" onPress={() => reset()}><View style={styles.inline}><RotateCcw color={colors.text} size={17} /><Text style={{ color: colors.text, fontWeight: '900' }}>Restart</Text></View></AppButton><Pressable accessibilityRole="button" onPress={() => void capture()} disabled={capturing} style={[styles.shutterOuter, { borderColor: colors.primary }]}><View style={[styles.shutterInner, { backgroundColor: capturing ? colors.textSecondary : colors.primary }]} /></Pressable><AppButton variant="secondary" onPress={() => router.replace({ pathname: '/solve', params: { puzzle } })}><Keyboard color={colors.text} size={19} /></AppButton></View><Text style={[styles.privacy, { color: colors.textSecondary }]}>Only averaged RGB values are kept between faces. The photographs remain in memory and are released when scanning finishes.</Text></Screen>;
}
const styles = StyleSheet.create({ chips: { flexDirection: 'row', gap: 8, marginBottom: 12 }, progress: { flexDirection: 'row', justifyContent: 'center', gap: 7, marginBottom: 12 }, dot: { width: 28, height: 5, borderRadius: 4 }, instruction: { gap: 5, marginBottom: 10 }, face: { fontSize: 13, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 0.8 }, instructionText: { fontSize: 13, lineHeight: 19 }, cameraShell: { alignSelf: 'center', overflow: 'hidden', borderRadius: 22, borderWidth: StyleSheet.hairlineWidth, backgroundColor: '#000' }, guide: { position: 'absolute', borderWidth: 2, borderColor: 'rgba(255,255,255,0.88)', borderRadius: 5, backgroundColor: 'rgba(255,255,255,0.06)' }, error: { textAlign: 'center', marginTop: 10, fontWeight: '700' }, actions: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 20, marginTop: 16 }, shutterOuter: { width: 72, height: 72, borderRadius: 36, borderWidth: 3, alignItems: 'center', justifyContent: 'center' }, shutterInner: { width: 56, height: 56, borderRadius: 28 }, inline: { flexDirection: 'row', alignItems: 'center', gap: 8 }, white: { color: '#fff', fontWeight: '900' }, privacy: { fontSize: 11, lineHeight: 17, textAlign: 'center', marginTop: 16 } });
