/**
 * GENERATED by .gen/kpattern-map-gen.ts — do not edit by hand.
 *
 * For each puzzle and KPuzzle orbit: `facelet[piece][ori]` is the index in
 * our canonical facelet string (lib/puzzle toFaceletString order) of the
 * sticker that piece shows at that orientation index when solved. Derived
 * mechanically from cubing.js move transformations and verified against
 * random scrambles on both models.
 */

export interface OrbitTable {
  name: string
  numOrientations: number
  facelet: number[][]
}

export const KPATTERN_TABLES: Record<"333" | "222" | "pyraminx", OrbitTable[]> = {
  "222": [
    {
      name: "CORNERS",
      numOrientations: 3,
      facelet: [
        [3, 4, 9],
        [1, 20, 5],
        [0, 16, 21],
        [2, 8, 17],
        [13, 11, 6],
        [12, 19, 10],
        [14, 23, 18],
        [15, 7, 22],
      ],
    },
  ],
  "333": [
    {
      name: "EDGES",
      numOrientations: 2,
      facelet: [
        [7, 19],
        [5, 10],
        [1, 46],
        [3, 37],
        [28, 25],
        [32, 16],
        [34, 52],
        [30, 43],
        [23, 12],
        [21, 41],
        [48, 14],
        [50, 39],
      ],
    },
    {
      name: "CORNERS",
      numOrientations: 3,
      facelet: [
        [8, 9, 20],
        [2, 45, 11],
        [0, 36, 47],
        [6, 18, 38],
        [29, 26, 15],
        [27, 44, 24],
        [33, 53, 42],
        [35, 17, 51],
      ],
    },
    {
      name: "CENTERS",
      numOrientations: 1,
      facelet: [
        [4],
        [40],
        [22],
        [13],
        [49],
        [31],
      ],
    },
  ],
  "pyraminx": [
    {
      name: "EDGES",
      numOrientations: 2,
      facelet: [
        [1, 21],
        [19, 12],
        [6, 33],
        [30, 15],
        [24, 28],
        [10, 3],
      ],
    },
    {
      name: "CORNERS",
      numOrientations: 3,
      facelet: [
        [2, 20, 11],
        [16, 23, 29],
        [7, 14, 34],
        [5, 32, 25],
      ],
    },
    {
      name: "CORNERS2",
      numOrientations: 3,
      facelet: [
        [0, 18, 9],
        [17, 22, 27],
        [8, 13, 35],
        [4, 31, 26],
      ],
    },
  ],
}
