import { useCallback, useEffect, useRef, useState } from 'react';
import * as Haptics from 'expo-haptics';
import { RefreshCw, Trash2 } from 'lucide-react-native';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { generateScramble, scrambleToString } from '@shared/scramble';

import { AppButton, Card, Chip, PageHeader, Screen, useAppTheme } from '@/components/ui';
import { readJson, type SolveRecord, storageKeys, writeJson } from '@/core/storage';

type TimerState = 'idle' | 'ready' | 'running' | 'stopped';
const CUBES = ['2x2', '3x3', '4x4', '5x5', '6x6', '7x7', 'pyraminx'] as const;
const formatTime = (ms: number) => { const minutes = Math.floor(ms / 60000); const seconds = Math.floor((ms % 60000) / 1000); const hundredths = Math.floor((ms % 1000) / 10); return minutes ? `${minutes}:${String(seconds).padStart(2, '0')}.${String(hundredths).padStart(2, '0')}` : `${seconds}.${String(hundredths).padStart(2, '0')}`; };
const average = (records: SolveRecord[], count: number) => records.length < count ? '—' : formatTime(records.slice(0, count).reduce((sum, item) => sum + item.timeMs, 0) / count);

export default function TimerScreen() {
  const colors = useAppTheme(); const [cube, setCube] = useState<(typeof CUBES)[number]>('3x3'); const [scramble, setScramble] = useState(''); const [timerState, setTimerState] = useState<TimerState>('idle'); const [time, setTime] = useState(0); const [solves, setSolves] = useState<SolveRecord[]>([]); const startRef = useRef(0); const intervalRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const nextScramble = useCallback(() => setScramble(scrambleToString(generateScramble(cube))), [cube]);
  useEffect(() => { nextScramble(); }, [nextScramble]);
  useEffect(() => { void readJson<SolveRecord[]>(storageKeys.solves, []).then(setSolves); }, []);
  useEffect(() => () => { if (intervalRef.current) clearInterval(intervalRef.current); }, []);
  const start = () => { startRef.current = Date.now(); setTime(0); setTimerState('running'); intervalRef.current = setInterval(() => setTime(Date.now() - startRef.current), 10); void Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light); };
  const stop = () => { if (intervalRef.current) clearInterval(intervalRef.current); intervalRef.current = null; const finalTime = Date.now() - startRef.current; setTime(finalTime); setTimerState('stopped'); const record: SolveRecord = { id: `${Date.now()}-${Math.random().toString(36).slice(2, 7)}`, timeMs: finalTime, cubeType: cube, scramble, createdAt: new Date().toISOString() }; setSolves((current) => { const next = [record, ...current]; void writeJson(storageKeys.solves, next); return next; }); nextScramble(); void Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success); };
  const onPressIn = () => { if (timerState === 'running') stop(); else setTimerState('ready'); };
  const onPressOut = () => { if (timerState === 'ready') start(); };
  const cubeSolves = solves.filter((solve) => solve.cubeType === cube);
  const clear = () => { setSolves((current) => { const next = current.filter((solve) => solve.cubeType !== cube); void writeJson(storageKeys.solves, next); return next; }); setTime(0); setTimerState('idle'); };
  return <Screen><PageHeader eyebrow="Stored on device" title="Timer" description="Hold to arm, release to start, then tap to stop." /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{CUBES.map((value) => <Chip key={value} label={value === 'pyraminx' ? 'Pyraminx' : value} selected={cube === value} onPress={() => setCube(value)} />)}</ScrollView><Card style={styles.scrambleCard}><Text style={[styles.scrambleLabel, { color: colors.textSecondary }]}>SCRAMBLE</Text><Text selectable style={[styles.scramble, { color: colors.text }]}>{scramble}</Text><Pressable accessibilityLabel="New scramble" onPress={nextScramble} style={styles.refresh}><RefreshCw color={colors.primary} size={19} /></Pressable></Card><Pressable onPressIn={onPressIn} onPressOut={onPressOut} style={[styles.timerPad, { backgroundColor: timerState === 'ready' ? colors.success : colors.backgroundElement, borderColor: timerState === 'ready' ? colors.success : colors.border }]}><Text style={[styles.time, { color: timerState === 'ready' ? '#fff' : colors.text }]}>{formatTime(time)}</Text><Text style={[styles.hint, { color: timerState === 'ready' ? '#fff' : colors.textSecondary }]}>{timerState === 'ready' ? 'Release to start' : timerState === 'running' ? 'Tap to stop' : 'Press and hold'}</Text></Pressable><View style={styles.stats}><Card style={styles.stat}><Text style={[styles.statValue, { color: colors.primary }]}>{cubeSolves.length}</Text><Text style={[styles.statLabel, { color: colors.textSecondary }]}>Solves</Text></Card><Card style={styles.stat}><Text style={[styles.statValue, { color: colors.accent }]}>{average(cubeSolves, 5)}</Text><Text style={[styles.statLabel, { color: colors.textSecondary }]}>Ao5</Text></Card><Card style={styles.stat}><Text style={[styles.statValue, { color: colors.success }]}>{average(cubeSolves, 12)}</Text><Text style={[styles.statLabel, { color: colors.textSecondary }]}>Ao12</Text></Card></View>{cubeSolves.length ? <><View style={styles.historyHeader}><Text style={[styles.historyTitle, { color: colors.text }]}>Recent solves</Text><AppButton variant="ghost" onPress={clear}><View style={styles.inline}><Trash2 color={colors.danger} size={16} /><Text style={{ color: colors.danger, fontWeight: '800' }}>Clear {cube}</Text></View></AppButton></View><View style={styles.history}>{cubeSolves.slice(0, 30).map((solve, index) => <Card key={solve.id} style={styles.solveRow}><Text style={[styles.solveIndex, { color: colors.textSecondary }]}>#{cubeSolves.length - index}</Text><Text style={[styles.solveTime, { color: colors.text }]}>{formatTime(solve.timeMs)}</Text><Text numberOfLines={1} style={[styles.solveScramble, { color: colors.textSecondary }]}>{solve.scramble}</Text></Card>)}</View></> : null}</Screen>;
}
const styles = StyleSheet.create({ chips: { gap: 8, paddingBottom: 14 }, scrambleCard: { minHeight: 118, justifyContent: 'center', alignItems: 'center', gap: 8, paddingHorizontal: 38 }, scrambleLabel: { fontSize: 11, fontWeight: '900', letterSpacing: 1.3 }, scramble: { textAlign: 'center', fontFamily: 'monospace', fontSize: 16, lineHeight: 24, fontWeight: '700' }, refresh: { position: 'absolute', right: 12, top: 12, padding: 8 }, timerPad: { minHeight: 250, borderRadius: 24, borderWidth: StyleSheet.hairlineWidth, marginTop: 14, justifyContent: 'center', alignItems: 'center', gap: 10 }, time: { fontSize: 62, lineHeight: 72, fontWeight: '300', fontVariant: ['tabular-nums'] }, hint: { fontSize: 14, fontWeight: '800' }, stats: { flexDirection: 'row', gap: 9, marginTop: 12 }, stat: { flex: 1, padding: 12 }, statValue: { fontSize: 19, fontWeight: '900', fontVariant: ['tabular-nums'] }, statLabel: { fontSize: 11, marginTop: 3 }, historyHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 24 }, historyTitle: { fontSize: 21, fontWeight: '900' }, inline: { flexDirection: 'row', gap: 7, alignItems: 'center' }, history: { gap: 8 }, solveRow: { flexDirection: 'row', alignItems: 'center', gap: 10, padding: 12 }, solveIndex: { width: 35, fontSize: 12 }, solveTime: { width: 76, fontSize: 17, fontWeight: '900', fontVariant: ['tabular-nums'] }, solveScramble: { flex: 1, fontFamily: 'monospace', fontSize: 11 } });
